### ISSUE TITLE
idl_a_demux_feed not removing dummy bytes correctly

### ISSUE THREAD

**Issue by ZXGuesser** [zapping-vbi/zvbi#51]
[This code](https://github.com/zapping-vbi/zvbi/blob/a48ab3a0d72efe9968ebafa34c425c892e4afa50/src/idl_demux.c#L186C1-L206C3) appears to be simply counting the total number of 0x00 and 0xFF bytes within an IDL A payload, and skipping a byte when either count reaches 8, rather than counting only _consecutive_ 0x00 or 0xFF bytes.

Additionally it appears to be skipping the 8th 0x00 or 0xFF byte rather than skipping the _following_ byte which I understand to be the position of the dummy byte.

**Comment by ileanadumitrescu95** [comment]
Thank you for your bug report and patch. The attached patch has been [merged](https://github.com/zapping-vbi/zvbi/commit/1f6a79cf330025dee0590b21f44d36a1058513c1).
